### ISSUE TITLE
Undefined variable "nnet" or class "nnet.internal.cnn.layer.Convolution2D"

### ISSUE THREAD

**Issue by Phalange96** [yechengxi/LightCapsNet#1]
Hi,thank you very much for your code,I ran your code but it gave me the error: 

 Undefined variable "nnet" or class "nnet.internal.cnn.layer.Convolution2D"
 conv_layer_2d (line 36)
            opts.layer{opts.current_layer}.conv2d_nntb=nnet.internal.cnn.layer.Convolution2D('conv2d_nntb', [k1,k2], k3,k4, [stride(1),stride(2)], pad(1:2:end));

I can't find the solution about it and I hope I can get  your generous help.
thanks a lot!

**Comment by yechengxi** [comment]
Please have neural network toolbox installed.

**Comment by farhadmath** [comment]
The error is still now in LightCapsNet. Please help me to fix the bug or update the conv_2d. file in LightCapsNet.

Please help me to fix the following bug in LightCapsNet:
Undefined function or variable
'PADDING_MODE'.

Error in conv_layer_2d (line 60)
            if PADDING_MODE==1

Error in net_bp (line 39)
                [res(layer).dzdx,
                res(layer).dzdw,res(layer).dzdb,opts]
                = conv_layer_2d(
                res(layer).x,net.layers{layer}.weights{1},net.layers{layer}.weights{2},net.layers{layer}.stride,net.layers{layer}.pad,res(layer+1).dzdx,opts
                );

Error in select_learning_rate (line
59)
                [ net,res,opts ] =
                net_bp( net,res,opts
                );

Error in selective_sgd (line 13)
        [lr_best]=select_learning_rate(net,opts);
        
Error in train_net (line 26)
        [ net,opts ] = selective_sgd(
        net,opts );

Error in TrainingScript (line 46)
    [net,opts]=train_net(net,opts);

Error in Main_Template (line 128)
    TrainingScript();

Error in Main_MNIST_Conv_Capsules
(line 30)
Main_Template(); %call training
template
